//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JwtInfrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JwtInfrastructure.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string Email_is_Required {
            get {
                return ResourceManager.GetString("Email_is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password Format.
        /// </summary>
        public static string inValid_Password {
            get {
                return ResourceManager.GetString("inValid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price less than or more than expected.
        /// </summary>
        public static string Less_than_or_exceeded_range_price {
            get {
                return ResourceManager.GetString("Less_than_or_exceeded_range_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string Name_is_Required {
            get {
                return ResourceManager.GetString("Name_is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_is_required {
            get {
                return ResourceManager.GetString("Password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter, one lowercase letter, one digit, one special character, and be at least 8 characters long..
        /// </summary>
        public static string Password_Policy {
            get {
                return ResourceManager.GetString("Password_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string Please_enter_a_valid_email_address {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Added.
        /// </summary>
        public static string ProductAdd {
            get {
                return ResourceManager.GetString("ProductAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Required.
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is Required.
        /// </summary>
        public static string ProductRequired {
            get {
                return ResourceManager.GetString("ProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Password Incorrect.
        /// </summary>
        public static string User_Or_Password_Incorrect {
            get {
                return ResourceManager.GetString("User_Or Password_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is Required.
        /// </summary>
        public static string Username_is_Required {
            get {
                return ResourceManager.GetString("Username_is_Required", resourceCulture);
            }
        }
    }
}
